# -*- coding: utf-8 -*-
"""
ASCII-Key -> korrekter Anzeigename (Umlaute/Diakritika), fuer alle Stationen der
5 neuen Linien. Wo eine Station bereits in der bestehenden RENetz_2030-Datei
existiert, wird EXAKT der dortige Anzeigename uebernommen (fuer Wiederverwendung
des gleichen Placemarks).
"""

DISPLAY_NAMES = {
    # --- RE71 Brandenburg-Hel: Deutschland (bereits vorhanden, exakte Namen aus Baseline) ---
    "Brandenburg Hbf": "Brandenburg Hbf",
    "Potsdam Hbf": "Potsdam Hauptbahnhof",
    "Berlin-Wannsee": "Berlin-Wannsee",
    "Berlin Hbf tief": "Berlin Hauptbahnhof",
    "Berlin Potsdamer Platz": "Berlin Potsdamer Platz",
    "Flughafen BER": "Flughafen BER",
    "Bernau b Berlin": "Bernau (b Berlin)",
    "Eberswalde Hbf": "Eberswalde Hbf",
    "Angermuende": "Angermünde",
    "Pasewalk": "Pasewalk",
    # --- RE71: Polen (neu, polnische Schreibweise mit Diakritika) ---
    "Szczecin Glowny": "Szczecin Główny",
    "Runowo Pomorskie": "Runowo Pomorskie",
    "Szczecinek": "Szczecinek",
    "Chojnice": "Chojnice",
    "Starogard Gdanski": "Starogard Gdański",
    "Tczew": "Tczew",
    "Gdansk Glowny": "Gdańsk Główny",
    "Gdansk Wrzeszcz": "Gdańsk Wrzeszcz",
    "Gdansk Zaspa": "Gdańsk Zaspa",
    "Gdynia Wzgorze Sw Maksyma": "Gdynia Wzgórze Św. Maksymiliana",
    "Gdynia Glowna": "Gdynia Główna",
    "Gdynia Chylonia": "Gdynia Chylonia",
    "Rumia Janowo": "Rumia Janowo",
    "Rumia": "Rumia",
    "Reda": "Reda",
    "Mrzezino": "Mrzezino",  # Dorf in Gmina Puck (Kaschubei) an der Bahnstrecke Reda-Hel, keine Diakritika im Ortsnamen
    "Zelistrzewo": "Żelistrzewo",
    "Puck": "Puck",
    "Swarzewo": "Swarzewo",
    "Wladyslawowo": "Władysławowo",
    "Wladyslawowo Port": "Władysławowo Port",
    "Chalupy": "Chałupy",
    "Kuznica": "Kuźnica",
    "Jastarnia": "Jastarnia",
    "Jurata": "Jurata",
    "Hel": "Hel",

    # --- S10 Ringbahn Ruhrgebiet (viele bereits vorhanden) ---
    "Unna Hbf": "Unna Hbf",
    "Unna West": "Unna West",
    "Massen": "Massen",
    "Dortmund-Wickede": "Dortmund-Wickede",
    "Dortmund-Brackel": "Dortmund-Brackel",
    "Dortmund Hauptbahnhof": "Dortmund Hauptbahnhof",
    "Dortmund-Dorstfeld": "Dortmund-Dorstfeld",
    "Dortmund-Dorstfeld Sued": "Dortmund-Dorstfeld Süd",
    "Dortmund-Universitaet": "Dortmund-Universität",
    "Dortmund-Oespel": "Dortmund-Oespel",
    "Dortmund-Kley": "Dortmund-Kley",
    "Bochum-Langendreer": "Bochum-Langendreer",
    "Bochum-Langendreer West": "Bochum-Langendreer West",
    "Bochum Hauptbahnhof": "Bochum Hauptbahnhof",
    "Bochum-Bermuda3eck": "Bochum-Bermuda3eck",
    "Bochum West": "Bochum West",
    "Bochum-Hamme": "Bochum-Hamme",
    "Bochum-Riemke": "Bochum-Riemke",
    "Wanne-Eickel Hbf": "Wanne-Eickel Hbf",
    "Gelsenkirchen Hbf": "Gelsenkirchen Hauptbahnhof",
    "Gelsenkirchen-Zollverein Nord": "Gelsenkirchen-Zollverein Nord",
    "Essen-Altenessen": "Essen-Altenessen",
    "Essen-Borbeck": "Essen-Borbeck",
    "Essen-Dellwig Ost": "Essen-Dellwig Ost",
    "Oberhausen Hbf": "Oberhausen Hauptbahnhof",
    "Muelheim-Styrum": "Mülheim-Styrum",
    "Muelheim West": "Mülheim West",
    "Muelheim Ruhr Hbf": "Mülheim (Ruhr) Hauptbahnhof",
    "Essen-Frohnhausen": "Essen-Frohnhausen",
    "Essen West": "Essen West",
    "Essen Hauptbahnhof": "Essen Hauptbahnhof",
    "Essen-Steele": "Essen-Steele",
    "Essen-Steele Ost": "Essen-Steele Ost",
    "Essen-Eiberg": "Essen-Eiberg",
    "Bochum-Hoentrop": "Bochum-Höntrop",
    "Bochum-Kohlenstrasse": "Bochum-Kohlenstraße",
    "Bochum-Stahlhausen": "Bochum-Stahlhausen",
    "Witten Hbf": "Witten Hbf",
    "Wengern": "Wengern Ost",  # identischer Knoten wie S3/S30 "Wengern Ost" (Verknuepfung S10, laut PDF)
    "Hagen-Vorhalle": "Hagen-Vorhalle",
    "Schwerte Ruhr": "Schwerte (Ruhr)",
    "Holzwickede": "Holzwickede",

    # --- S3/S30 Ruhr-Volme-Netz ---
    "Essen-Horst": "Essen-Horst",
    "Bochum-Dahlhausen": "Bochum-Dahlhausen",
    "Hattingen Ruhr": "Hattingen (Ruhr)",
    "Hattingen Mitte": "Hattingen Mitte",
    "Heinrichshuette": "Heinrichshütte",
    "Blankenstein Burg": "Blankenstein Burg",
    "Haus Kemnade": "Haus Kemnade",
    "Herbede": "Herbede",
    "Ruine Hardenstein": "Ruine Hardenstein",
    "Zeche Nachtigall": "Zeche Nachtigall",
    "Witten Bommern": "Witten-Bommern",
    "Wengern Ost": "Wengern Ost",
    "Hagen Hauptbahnhof": "Hagen Hauptbahnhof",
    "Dahl": "Dahl",
    "Rummenohl": "Rummenohl",
    "Dahlerbrueck": "Dahlerbrück",
    "Schalksmuehle": "Schalksmühle",
    "Luedenscheid Hbf": "Lüdenscheid Hbf",

    # --- RE17 Oesterport-Rostock: Daenemark/Deutschland ---
    "Oesterport": "Østerport",
    "Koebenhavn H": "København H",
    "Noerreport": "Nørreport",
    "Koege Nord": "Køge Nord",
    "Naestved": "Næstved",
    "Vordingborg": "Vordingborg",
    "Ringsted": "Ringsted",
    "Nykoebing Falster": "Nykøbing Falster",
    "Roedby": "Rødby",
    "Luebeck Hbf": "Lübeck Hauptbahnhof",
    "Bad Kleinen": "Bad Kleinen",
    "Rostock Hauptbahnhof": "Rostock Hauptbahnhof",
    "Grossenbrode Heiligenhafen": "Großenbrode/Heiligenhafen",
    "Oldenburg in Holstein": "Oldenburg in Holstein",
    "Scharbeutz": "Scharbeutz",
    "Timmendorfer Strand Ratekau": "Timmendorfer Strand/Ratekau",
    "Bad Schwartau": "Bad Schwartau",
    "Buetzow": "Bützow",

    # --- RE30 Leeuwarden-Winterberg/Duesseldorf: Niederlande/Deutschland ---
    "Leeuwarden": "Leeuwarden",
    "Meppel": "Meppel",
    "Zwolle": "Zwolle",
    "Almelo": "Almelo",
    "Hengelo": "Hengelo",
    "Bad Bentheim": "Bad Bentheim",
    "Rheine": "Rheine",
    "Muenster Westf Hbf": "Münster (Westf) Hauptbahnhof",
    "Drensteinfurt": "Drensteinfurt",
    "Hamm Westf Hbf": "Hamm (Westf) Hbf",
    "Unna": "Unna Hbf",  # identische Station wie S10 "Unna Hbf"
    "Froendenberg": "Fröndenberg",
    "Wickede Ruhr": "Wickede (Ruhr)",
    "Arnsberg Westf": "Arnsberg (Westf)",
    "Bestwig": "Bestwig",
    "Bigge": "Bigge",
    "Steinhelle": "Steinhelle",
    "Siedlinghausen": "Siedlinghausen",
    "Silbach": "Silbach",
    "Winterberg Westf": "Winterberg (Westf)",
    "Schwelm": "Schwelm",
    "Wuppertal-Oberbarmen": "Wuppertal-Oberbarmen",
    "Wuppertal Hauptbahnhof": "Wuppertal Hauptbahnhof",
    "Wuppertal-Vohwinkel": "Wuppertal-Vohwinkel",
    "Duesseldorf Hauptbahnhof": "Düsseldorf Hauptbahnhof",
}

# Liniennamen / Richtungs- und Beschreibungstexte, die NICHT ueber Stationskeys
# laufen (Linientitel etc.) - hier zentral, damit die ue/oe/ae/ss-Pruefung auch
# hierueber laeuft.
LINE_TITLE_DISPLAY = {
    "RE71": "RE71 Brandenburg Hbf-Hel",
    "S10": "S10 Ringbahn Ruhrgebiet",
    "S3": "S3 Essen Hbf-Hattingen Mitte",
    "S30": "S30 Essen Hbf-Lüdenscheid Hbf",
    "RE17": "RE17 Østerport-Rostock",
    "RE30_A": "RE30 Leeuwarden-Winterberg (Westf)",
    "RE30_B": "RE30 Leeuwarden-Düsseldorf Hbf",
}
